spring:
  profiles:
    active:
      - dev

---

spring:
  profiles: default
  datasource:
    url: ${DATABASE_PERSON_REGISTER_API_URL}
    username: ${DATABASE_PERSON_REGISTER_API_USERNAME}
    password: ${DATABASE_PERSON_REGISTER_API_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
        show_sql: false
        format_sql: false
  liquibase:
    change-log: classpath:/resources/liquibase/changelog.yaml
server:
  port: 8080
  servlet:
    context-path: /api