CREATE TABLE PERSON (
  ID RAW(36) CONSTRAINT PERSON_PK NOT NULL PRIMARY KEY,
  CREATED_TIMESTAMP TIMESTAMP NOT NULL,
  UPDATED_TIMESTAMP TIMESTAMP NOT NULL,
  BIRTHDATE DATE NOT NULL,
  NAME VARCHAR2(40) NOT NULL,
  CPF VARCHAR2(11) NOT NULL UNIQUE,
  "STATUS" VARCHAR2(20) NOT NULL
) TABLESPACE PERSON_REGISTER_API_DATA