CREATE TABLE PERSON (
  ID RAW(36) CONSTRAINT PERSON_PK NOT NULL PRIMARY KEY,
  BIRTHDATE DATE NOT NULL,
  NAME VARCHAR(40) NOT NULL,
  CPF VARCHAR(11) NOT NULL UNIQUE
) TABLESPACE PERSON_REGISTER_API_DATA